name: Teste
description: "teste"
labels: ["Teste"]
body:
  - type: dropdown
    id: resource
    attributes:
      label: "Resource"
      options:
        - label: "Bastion"
          value: "bastion"
    validations:
      required: true
